--- 基础设置
require('basic')
require('plugins')
require('colorscheme')
require('keybindings')
-- 插件配置
require("plugin-config.nvim-tree")
--require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
require("plugin-config.telescope")
require("plugin-config.autopairs")
require("plugin-config.neoscroll")
require("plugin-config.trouble")
require("plugin-config.toggleterm")
require("plugin-config.command")
require("plugin-config.illuminate")
require("plugin-config.comment")
-- 内置LSP 
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("plugin-config.indent-blankline")
require("lsp.null-ls")
